import "./globals.css";
import makeStore from "@/store/notesSlice";

import StoreProvider from "@/store/StoreProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider store={makeStore}>{children}</StoreProvider>
      </body>
    </html>
  );
}
